//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResourceItem.proto
namespace AutoPb//ResourceItem
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceItem")]
  public partial class ResourceItem : global::ProtoBuf.IExtensible
  {
    public ResourceItem() {}
    
    private string _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private long _Size;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Size
    {
      get { return _Size; }
      set { _Size = value; }
    }
    private long _OriginalSize;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"OriginalSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long OriginalSize
    {
      get { return _OriginalSize; }
      set { _OriginalSize = value; }
    }
    private string _Key;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private string _Folder;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Folder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Folder
    {
      get { return _Folder; }
      set { _Folder = value; }
    }
    private string _Path;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Path
    {
      get { return _Path; }
      set { _Path = value; }
    }

    public override string ToString()
    {
        string str = "";
        System.Reflection.PropertyInfo[] property = this.GetType().GetProperties();
        foreach (System.Reflection.PropertyInfo pInfo in property)
        {
            str = string.Format("{0}  {1} {2} : ", str, pInfo.Name.ToString(), pInfo.GetValue(this, null).ToString());
        }
        return str;
    }

  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}